config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "sessions#new"
  get "sign_up" , to: "registrations#new"
  post "sign_up" , to: "registrations#create"

  get "sign_in" , to: "sessions#new"
  post "sign_in" , to: "sessions#create"
  delete "sign_out", to: "sessions#destroy"

  get "owner_sign_in" , to: "owner/sessions#new"
  post "owner_sign_in" , to: "owner/sessions#create"
  delete "owner_sign_out", to: "owner/sessions#destroy"

  namespace :owner do
    root to: 'owners#index'
    resources :menus, only: [:index,:new,:create,:edit,:update,:destroy]
    resources :orders, only: [:index]
  end 

  get "/orders/cart", to: "orders#cart", as: :carts
  get "orders/index", to: "orders#index"
  put"/order_items/:id/decrement", to:"order_items#decrement"
  put"/order_items/:id/decrementInCart", to:"order_items#decrementInCart"

  post "/order_items/:id/addToCart", to:"order_items#addToCart"

  put"/order_items/:id/increment", to:"order_items#increment"
  put"/order_items/:id/incrementInCart", to:"order_items#incrementInCart"

  delete "/order_items/:id", to: "order_items#destroy"
  post "/orders/confirm", to: "orders#confirm"
  
  get "/orders", to: "owner/orders#index"

  get "/order_items/:id/viewOrderItems", to: "order_items#viewOrderItems"
  resources :menus
  resources :owners
  resources :orders
end

app/models/menu.rb
class Menu < ApplicationRecord
    
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    before_action :ensure_user_logged_in
    
    def index
        @menus = Menu.all
        if session[:current_order_id] == nil
            orders = Order.where(user_id: current_user.id)
            if orders
              previous_order = orders.find_by(status: "notprocessed")
              if previous_order
                session[:current_order_id] = previous_order.id
              end
            end
            if session[:current_order_id] == nil
              user_id = current_user.id
              order = Order.create!(user_id: user_id, date: DateTime.now, delivered_at: nil, status: "notprocessed", price: 0)
              session[:current_order_id] = order.id
            end
        end
    end
end

app/controllers/owner/menus_controller.rb
class Owner::MenusController < ApplicationController

    def index
        @menus = Menu.all.order(:created_at)
    end

    def new 
        @menu = Menu.new
    end

    def create
        @menu = Menu.new(menu_params)
        if @menu.save
            flash[:notice] = "Menu Added"
            redirect_to owner_menus_path
        else
            flash[:notice] = "Menu can't be blank"
            render 'owner/menus/new'
        end
    end

    def edit
        @menu = Menu.find(params[:id])
    end

    def update
        @menu = Menu.find(params[:id])
        if @menu.update(menu_params)
            flash[:notice] = "Menu updated"
            redirect_to owner_menus_path
        else
            flash[:error] = "Update failed"
            redirect_to edit_menu_owner_path
        end  
    end

    def destroy
        Menu.destroy(params[:id])
        flash[:notice] = "Menu removed!"
        redirect_to owner_menus_path
    end

    private
        def menu_params
            params.require(:menu).permit(:name,:price)
        end

end

app/views/menus/index.html.erb
<h1 class="main-title"> Food Order </h1>
<div class="topnav">
    <%= link_to "Home", menus_path %>
    <%= link_to "Cart", carts_path %>
     <%= link_to "Orders", orders_index_path %>
    <%= button_to "Sign out", sign_out_path , method: :delete%>
</div>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>

<% if @current_user %>
    <h1 class="main-header">Welcome <%= @current_user.name %>! <h1>
<%end%>

<h1 class="menu-title"> Menu List </h1>

<div class="menu-container">
    <% @menus.each do |menu| %>
        <div class="menu-item-container">
            <p>Name : <%= menu.name %></p>
            <p>Price : <%= menu.price%></p>
            <% order_item = Order.find(session[:current_order_id]).order_items.find_by(menu_id: menu.id) %>
            <div>
                <% if order_item %>
                    <%= form_with(url: "/order_items/#{menu.id}/decrement", method: :put) do%>
                    <%= submit_tag("-",class: "decrement-button")%>
                    <% end %>
                    <p><%= order_item.quantity%></p>
                    <%= form_with(url: "/order_items/#{menu.id}/increment", method: :put) do%>
                    <%= submit_tag("+", class: "increment-button")%>
                    <% end %>
                <% else %>
                    <%= form_with(url: "/order_items/#{menu.id}/addToCart", method: :post) do%>
                    <%= submit_tag("Add to Cart",class: "cart-button")%>
                    <% end %>
                <%end%>
            </div>
        </div>
    <% end %>
</div>
<br>