config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "sessions#new"
  get "sign_up" , to: "registrations#new"
  post "sign_up" , to: "registrations#create"

  get "sign_in" , to: "sessions#new"
  post "sign_in" , to: "sessions#create"
  delete "sign_out", to: "sessions#destroy"

  get "owner_sign_in" , to: "owner/sessions#new"
  post "owner_sign_in" , to: "owner/sessions#create"
  delete "owner_sign_out", to: "owner/sessions#destroy"

  namespace :owner do
    root to: 'owners#index'
    resources :menus, only: [:index,:new,:create,:edit,:update,:destroy]
    resources :orders, only: [:index]
  end 

  get "/orders/cart", to: "orders#cart", as: :carts
  get "orders/index", to: "orders#index"
  put"/order_items/:id/decrement", to:"order_items#decrement"
  put"/order_items/:id/decrementInCart", to:"order_items#decrementInCart"

  post "/order_items/:id/addToCart", to:"order_items#addToCart"

  put"/order_items/:id/increment", to:"order_items#increment"
  put"/order_items/:id/incrementInCart", to:"order_items#incrementInCart"

  delete "/order_items/:id", to: "order_items#destroy"
  post "/orders/confirm", to: "orders#confirm"
  
  get "/orders", to: "owner/orders#index"

  get "/order_items/:id/viewOrderItems", to: "order_items#viewOrderItems"
  resources :menus
  resources :owners
  resources :orders
end

app/models/menu.rb
class Menu < ApplicationRecord
    
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_secure_password

    validates :email, presence: true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    before_action :ensure_user_logged_in
    
    def index
        @menus = Menu.all
        if session[:current_order_id] == nil
            orders = Order.where(user_id: current_user.id)
            if orders
              previous_order = orders.find_by(status: "notprocessed")
              if previous_order
                session[:current_order_id] = previous_order.id
              end
            end
            if session[:current_order_id] == nil
              user_id = current_user.id
              order = Order.create!(user_id: user_id, date: DateTime.now, delivered_at: nil, status: "notprocessed", price: 0)
              session[:current_order_id] = order.id
            end
        end
    end
end

app/controllers/owner/menus_controller.rb
class Owner::MenusController < ApplicationController

    def index
        @menus = Menu.all.order(:created_at)
    end

    def new 
        @menu = Menu.new
    end

    def create
        @menu = Menu.new(menu_params)
        if @menu.save
            flash[:notice] = "Menu Added"
            redirect_to owner_menus_path
        else
            flash[:notice] = "Menu can't be blank"
            render 'owner/menus/new'
        end
    end

    def edit
        @menu = Menu.find(params[:id])
    end

    def update
        @menu = Menu.find(params[:id])
        if @menu.update(menu_params)
            flash[:notice] = "Menu updated"
            redirect_to owner_menus_path
        else
            flash[:error] = "Update failed"
            redirect_to edit_menu_owner_path
        end  
    end

    def destroy
        Menu.destroy(params[:id])
        flash[:notice] = "Menu removed!"
        redirect_to owner_menus_path
    end

    private
        def menu_params
            params.require(:menu).permit(:name,:price)
        end

end

app/controllers/owner/orders_controller.rb
class Owner::OrdersController < ApplicationController
    def index
        @orders = Order.all
    end

end

app/controllers/owner/sessions_controller.rb
class Owner::SessionsController < ApplicationController
    def new
        render 'owner/sessions/new'
    end


    def create
        owner = Owner.find_by(email: params[:email])
        if owner.present? && owner.authenticate(params[:password])
            redirect_to owners_path , notice: "Logged in Successfully"
        else
            redirect_to owner_sign_in_path, alert: "Incorrect Email or Password "
        end
    end

    def destroy
        flash[:notice] = "Signed Out successfully"
        redirect_to owner_sign_in_path
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    def index
        render "owner/index"
    end
end

app/views/owner/menus/edit.html.erb
<div class="main-container">
    <h1 class="main-title"> Edit Menu Here </h1> 


    <%= form_with model: @menu, url: owner_menu_path, method: :patch  do|f|%>
        <div>
            <%= f.label :name,class:"form-label"%><br />
            <%= f.text_field :name, autofocus: true %>
        </div>

        <div>
            <%= f.label :price,class:"form-label" %><br />
            <%= f.number_field :price, autofocus: true %>
        </div>

        <div >
            <%= f.submit "Update Menu", :action =>'update',class: "button" %>
        </div>
        <% if flash[:notice] %>
            <div class="notice"><%= flash[:notice] %></div>
        <% end %>
    <% end%>

    <%= link_to 'Back to Menu List', owner_menus_path,class: "to-button"%>
</div>

app/views/owner/menus/index.html.erb
<h1 class="main-title"> Food Order Owner Dashboard</h1>
<div class="topnav">
    <%= link_to "Home", owners_path %>
    <%= link_to "Menu Details", owner_menus_path %>
     <%= link_to "Order Details", owner_orders_path %>
    <%= button_to "Sign out", owner_sign_out_path , method: :delete%>
</div>
<div class="clear-float">
</div>
<br>
<br>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

 <%= link_to "Add Menu" , new_owner_menu_path,class: "add-button"%>
 <br>
 <br>
<table class="menu-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Edit </th>
      <th>Delete </th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.price%></td>
        <td><%= link_to "Edit", edit_owner_menu_path(menu.id),class:"edit-button" %></td>
        <td><%= button_to "Delete", owner_menu_path(menu.id), method: :delete,class: "delete-button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/owner/menus/new.html.erb
<div class="main-container">
    <h1 class="main-title"> Add new menu </h1>


    <%= form_with model: @menu, url: owner_menus_path, method: :post do |f| %>
        <div>
            <%= f.label :name ,class: "form-label"%><br />
            <%= f.text_field :name, autofocus: true %>
        </div>

        <div>
            <%= f.label :price ,class:"form-label"%><br />
            <%= f.number_field :price, autofocus: true %>
        </div>

        <div >
            <%= f.submit "ADD", class:"button" %>
        </div>
    <% end%>


    <%= link_to 'Back to Menu List', owner_menus_path, class: "to-button"%>
</div>